import { Upload, Link2, BarChart2 } from 'lucide-react'

const STEPS = [
  {
    num: '01',
    icon: Upload,
    title: 'Upload your SSH key',
    desc: 'Upload or paste your SSH private key and enter your server IP. Run ClawDesk on storage you control and keep key material out of API responses.',
    code: '$ openclaw gateway start --port 3284',
  },
  {
    num: '02',
    icon: Link2,
    title: 'Link your agent',
    desc: 'Enter the gateway token generated by your OpenClaw instance. ClawDesk connects in seconds and starts streaming live data.',
    code: 'gateway token: mc_gw_xxxxxxxxxxxxxxxx',
  },
  {
    num: '03',
    icon: BarChart2,
    title: 'Monitor & control',
    desc: 'View live logs, restart agents, edit configs, run SSH commands, and manage your team from one dense, information-packed dashboard.',
    code: '[OK] agent "prod-01" connected · uptime 4d 12h',
  },
]

export function HowItWorks() {
  return (
    <section className="py-20 px-6 border-y border-border-1" id="how-it-works">
      <div className="max-w-5xl mx-auto">
        <div className="text-center mb-12 space-y-2">
          <p className="text-xs font-semibold uppercase tracking-wider text-rose-400">Setup</p>
          <h2 className="text-3xl font-bold text-white">Up and running in 3 steps</h2>
        </div>
        <div className="grid md:grid-cols-3 gap-8">
          {STEPS.map((step, i) => {
            const Icon = step.icon
            return (
              <div key={i} className="relative">
                {i < STEPS.length - 1 && (
                  <div className="hidden md:block absolute top-6 left-[calc(100%+1px)] w-8 h-px opacity-60" style={{ backgroundImage: 'linear-gradient(to top, #ff0844 0%, #ffb199 100%)' }} />
                )}
                <div className="space-y-3">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-rose-500/10 border border-rose-500/20 flex items-center justify-center">
                      <Icon size={16} className="text-rose-400" />
                    </div>
                    <span className="text-3xl font-black text-border-2 select-none">{step.num}</span>
                  </div>
                  <h3 className="text-sm font-bold text-white">{step.title}</h3>
                  <p className="text-xs text-zinc-500 leading-relaxed">{step.desc}</p>
                  <div className="bg-surface-2 border border-border-1 rounded-lg px-3 py-2">
                    <code className="text-2xs font-mono text-emerald-400">{step.code}</code>
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      </div>
    </section>
  )
}
